// This isn't really auto-generated, but we add this tag so that StyleCop ignores it
// since this file is directly included as source to many projects with a variety of
// stylecop rules enabled.
// <auto-generated />

//Ref: %VSRoot%\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.Telemetry.dll

//Ref: %PerfGraphVSIX%

//Pragma: verbose=false

using System;
using System.Threading;
using System.IO;
using System.Diagnostics;
using System.Runtime.InteropServices;
using Microsoft.Win32;
using PerfGraphVSIX;
using Microsoft.Test.Stress;
using System.Threading.Tasks;
using Microsoft.VisualStudio.Telemetry;

namespace MyNameSpace
{
    // except for MyClass, most of this file is from https://devdiv.visualstudio.com/DevDiv/_git/VS?path=%2Fsrc%2Fvscommon%2FCodeMarkers%2FManagedCodeMarkers.cs

    public class MyClass
    {
        public ILogger _logger; // log to PerfGraph ToolWindow
        public CancellationToken _CancellationTokenExecuteCode;
        public static async Task DoMain(object[] args)
        {
            var ox = new MyClass();
            await ox.DoItAsync(args);
        }

        async Task DoItAsync(object[] args)
        {
            var FileToExecute = args[0] as string;
            _logger = args[1] as ILogger;
            _CancellationTokenExecuteCode = (CancellationToken)args[2]; // value type
            var itakeSample = args[3] as ITakeSample;
            var package = args[5] as object;// IAsyncPackage;
            while (!_CancellationTokenExecuteCode.IsCancellationRequested)
            {
                var ev = "PerfGraphVSIX/Telemetry/EventFromCodeSample";
                _logger.LogMessage($"Sending TelemetryEvent '{ev}'");
                TelemetryService.DefaultSession.PostEvent(ev);
                await Task.Delay(TimeSpan.FromSeconds(1));
                // verified
                /*
            // this really works, as verified by a PerfView trace with CodeMarker provider enabled:
            // additional providers = 641d7f6c-481c-42e8-ab7e-d18dc5e5cb9e:@StacksEnabled=true
Name
+ Process64 devenv (18828) Args:   /rootsuffix exp
 + Thread (43528) CPU=119ms
  + ntdll!?
   + kernel32!?
    + devenv!?
     + msenv!?
      + user32!?
       + ?!?
        + windowsbase.ni!?
         + mscorlib.ni!?
          + windowsbase.ni!?
           + mscorlib.ni!?
            + tmpbdfd!MyNameSpace.MyClass+<DoItAsync>d__3.MoveNext()
             + microsoft.visualstudio.telemetry.ni!?
              + microsoft.visualstudio.telemetry.package.ni!?
               + Microsoft.VisualStudio.Telemetry.Package!VSTelemetryEtwProvider.WriteTelemetryEvent
                + microsoft.visualstudio.utilities.ni!?
                 + mscorlib!EventSource.WriteImpl
                  + mscorlib.ni!?
                   + ntdll!?
                    + wow64!?
                     + wow64cpu!?
                      + wow64!?
                       + ntdll!?
                        + Event Microsoft-VisualStudio-Common/perfgraphvsix_telemetry_eventfromcodesample
                
                 */
            }
        }
    }
}
